GreedyBookProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # import settings
from django.conf.urls.static import static  #import static here
from .views import home_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/',include('profilesApp.urls', namespace='profiles')),
    path('posts/',include('postsApp.urls', namespace='postsApp')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#run py manage.py collectstatic

postsApp/urls.py
from django.urls import path
from .views import post_comment_create_list_view, like_unlike_post,PostDeleteView,PostUpdateView

app_name = 'postsApp'

urlpatterns = [
    path('', post_comment_create_list_view,name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/',PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/',PostUpdateView.as_view(), name='post-update'),
]

profilesApp/urls.py
from django.urls import path
from .views import ProfileDetailView, acceptInvitations, rejectInvitations, remove_from_friends, send_invitation,my_profile_view, invites_received_view,profiles_list_view, invite_profiles_list_view, ProfilelistView

app_name = 'profilesApp'

urlpatterns = [
    path('', ProfilelistView.as_view(), name='all-profiles-view'),
    path('myprofile/' ,my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invites/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', acceptInvitations, name='accept-invite'),
    path('my-invites/reject/', rejectInvitations, name='reject-invite'),
]

templates/main/home.html
{% extends 'base.html' %}


{% block title %}
Home
{% endblock title %}

{% block content %}
{{hello}}
<br>
{{user}}
{% endblock content %}

{% block scripts %}

{% endblock scripts %}

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'postsApp:main-post-view' as path_to_posts %}

{% url 'profilesApp:my-profile-view' as path_to_my_profile %}
{% url 'profilesApp:my-invites-view' as path_to_my_invites %}
{% url 'profilesApp:invite-profiles-view' as path_to_invites %}
{% url 'profilesApp:all-profiles-view' as path_to_all_profiles %}
{% url 'account_logout' as path_to_logout %}
{% url 'account_logout' as path_to_logout %}
{% url 'account_login' as path_to_login %}

<div class="ui inverted menu nav -mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>GreedyBook</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Dashboard
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Send Invites
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp;<div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="Search Friends">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image"> &nbsp;
                Hello! &nbsp; {{profile.user}}
            </a>

            <a href="{{path_to_logout}}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{{path_to_login}}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>